version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgres://exampleuser:examplepass@db:5432/exampledb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
