version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: omer
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: omer@db.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db

  api:
    build: .
    environment:
      DATABASE_URL: postgres://omer:1234@db:5432/mydb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
